# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
