# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entry_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='identifier',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
    ]
