# Generated by Django 3.1.5 on 2021-01-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_entry_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='text',
        ),
    ]
