# Generated by Django 3.1.5 on 2021-01-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_entry_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='format',
            field=models.CharField(default='md', max_length=10),
        ),
    ]
